#!/usr/bin/python

# Copyright: (c) 2018, Itential <opensource@itential.com>
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)
"""
This module provides details of a workflow from Itential Automation Platform
"""
from __future__ import absolute_import, division, print_function
__metaclass__ = type

ANSIBLE_METADATA = {'metadata_version': '1.1',
                    'status': ['preview'],
                    'supported_by': 'community'}

DOCUMENTATION = '''
---
module: iap_workflow_details
version_added: "2.8"
author: "Itential (opensource@itential.com)"
short_description: Get details of workflow from the Itential Automation Platform
description:
  - This will get the details of a workflow from the Itential Automation Platform.
options:
  iap_port: 
    description: 
      - Provide the port number for the Itential Automation Platform  
    type: string
    required: true
    default: null

  iap_fqdn: 
    description: 
      - Provide the fqdn for the Itential Automation Platform  
    type: string
    required: true
    default: null

  token_key: 
    description: 
      - Token key generated by iap_token module for the Itential Automation Platform 
    type: string
    required: true
    default: null

  workflow_name: 
    description: 
      - Provide the workflow name 
    type: string
    required: true
    default: null
  
  https: 
    description: 
      - The transport protocol is HyperText Transfer Protocol Secure (HTTPS) for the Itential Automation Platform 
      - By default using http
    type: bool
    default: False
    
requirements:
  - the Itential Automation Platform with relevant applications

notes:
  - This module is under construction

'''

EXAMPLES = '''
- name: Get details of workflow from the Itential Automation Platform
  iap_get_workflow_details:
    iap_port: 3000
    iap_fqdn: localhost
    token_key: "DFSFSFHFGFGF[DSFSFAADAFASD%3D"
    workflow_name: "RouterUpgradeWorkflow"
  register: result

- debug: var=result
'''

RETURN = '''
response:
    description: The result contains the response from the call
    type: object
    returned: always
msg:
    description: The msg will contain the error code or status of the workflow
    returned: always
'''

# Ansible imports
from ansible.module_utils.basic import AnsibleModule
from ansible.module_utils.urls import fetch_url


def get_workflow_details(module):
    """
    :param module:
    :return: response and msg
    """
    # defaulting the value for transport_protocol to be : http
    transport_protocol = 'http'
    if module.params['https'] is True:
        transport_protocol = 'https'

    application_token = module.params['token_key']
    url = transport_protocol + "://" + module.params['iap_fqdn'] + ":" + module.params[
        'iap_port'] + "/workflow_engine/workflows/detailed/" + \
          module.params['workflow_name'] + "?token=" + str(application_token)

    headers = dict()
    headers['Content-Type'] = 'application/json'

    # Using fetch url instead of requests
    response, info = fetch_url(module, url, headers=headers)
    response_code = str(info['status'])
    if info['status'] != 200 or 201:
        if info['status'] >= 400:
            module.fail_json(msg="Failed to connect to Itential Automation Platform. Response code is " + response_code)
        else:
            module.fail_json(msg="Failed to connect to Itential Automation Platform. Response code is " + response_code)

    # in the event of a successful module execution, you will want to
    # simple AnsibleModule.exit_json(), passing the key/value results
    response = response.read()
    module.exit_json(changed=True, msg={"workflow_name": module.params['workflow_name']},
                     response=response)


def main():
    """
    :return: response and msg
    """
    # define the available arguments/parameters that a user can pass to
    # the module
    # the AnsibleModule object will be our abstraction working with Ansible
    # this includes instantiation, a couple of common attr would be the
    # args/params passed to the execution, as well as if the module
    # supports check mode
    module = AnsibleModule(
        argument_spec=dict(
            iap_port=dict(type='str', required=True),
            iap_fqdn=dict(type='str', required=True),
            token_key=dict(type='str', required=True),
            workflow_name=dict(type='str', required=True),
            https=(dict(type='bool', default=False))
        )
    )
    get_workflow_details(module)


if __name__ == '__main__':
    main()